services:
  backend:
    build: ./backend
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5005/api
    depends_on:
      - backend